// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models;

public partial class AgvremoteSetting
{
    public int Agvid { get; set; }

    public int? ChargingDelaySecTime { get; set; }

    public int? BypassCheckCargoStatus { get; set; }
}