// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models
{
    public partial class InstrumentMeasureResult
    {
        public string CommandID { get; set; }
        public DateTime? Time { get; set; }
        public int? Result { get; set; }
        public string Position { get; set; }
        public string Illuminance { get; set; }
        public string Decibel { get; set; }
        public string Temperature { get; set; }
        public string Humidity { get; set; }
        public string IPA { get; set; }
        public string Acetone { get; set; }
        public string TVOC { get; set; }
        public string DustParticles1 { get; set; }
        public string DustParticles2 { get; set; }
        public string DustParticles3 { get; set; }
        public string DustParticles4 { get; set; }
        public string DustParticles5 { get; set; }
        public string DustParticles6 { get; set; }
        public string PID { get; set; }
    }
}