// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models;

public partial class MeasureInfo
{
    public string CommandId { get; set; }

    public DateTime? ReceiveTime { get; set; }

    public string Bay { get; set; }

    public string Points { get; set; }

    public int? InPoint { get; set; }

    public int? OutPoint { get; set; }

    public string SuccessPoints { get; set; }
}