// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models;

public partial class PathInfo
{
    public DateTime ChangeTime { get; set; }

    public int Agvid { get; set; }

    public int? Location { get; set; }
}