// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models;

public partial class Pmhistory
{
    public int Agvid { get; set; }

    public DateTime Pmdate { get; set; }

    public string UserName { get; set; }

    public string Comment { get; set; }
}