// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models
{
    public partial class PMSetting
    {
        public int AGVID { get; set; }
        public int? PMCount { get; set; }
        public int? DoneTaskCount { get; set; }
    }
}