// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models;

public partial class ProductInfo
{
    public string CommandId { get; set; }

    public string Id { get; set; }

    public DateTime ReceiveTime { get; set; }

    public string PartId { get; set; }

    public string LotId { get; set; }

    public string RecipeId { get; set; }

    public string LayerNo { get; set; }

    public string Frame { get; set; }

    public string Stamp { get; set; }

    public DateTime? InRackLdtime { get; set; }

    public DateTime? OvenLdtime { get; set; }

    public DateTime? OvenUldtime { get; set; }

    public DateTime? OutRackUldtime { get; set; }

    public string OutRackOpid { get; set; }

    public int? ProcessResultOfSystem { get; set; }

    public int? ProcessResultOfOutRack { get; set; }

    public string SerialId { get; set; }
}