// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models
{
    public partial class ProductInfo
    {
        public string ID { get; set; }
        public string CommandID { get; set; }
        public string PartID { get; set; }
        public string LotID { get; set; }
        public string RecipeID { get; set; }
        public string LayerNo { get; set; }
        public string Frame { get; set; }
        public string Stamp { get; set; }
        public DateTime? Receive_Time { get; set; }
        public DateTime? InRackLDTime { get; set; }
        public DateTime? OvenLDTime { get; set; }
        public DateTime? OvenULDTime { get; set; }
        public DateTime? OutRackULDTime { get; set; }
        public string OutRackOPID { get; set; }
        public int? ProcessResultOfSystem { get; set; }
        public int? ProcessResultOfOutRack { get; set; }
        public string SerialID { get; set; }
    }
}