// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models;

public partial class TrafficTask
{
    public int Agvid { get; set; }

    public string StartPos { get; set; }

    public string TargetPos { get; set; }

    public string FullPath { get; set; }

    public double Weight { get; set; }

    public string ShortPath { get; set; }

    public string InvolvePoint { get; set; }

    public string BookingPath { get; set; }

    public string CrossPoint { get; set; }

    public int CrossAgvid { get; set; }

    public string Message { get; set; }

    public string MessageCh { get; set; }
}