// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models;

public partial class UserGroup
{
    public string UserGroup1 { get; set; }

    public string Functions { get; set; }
}