// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KGSWebAGVSystemAPI.Models
{
    public partial class UserLoginLog
    {
        public string UserName { get; set; }
        public DateTime DateTime { get; set; }
        public string Operation { get; set; }
    }
}